services:
  hub-service:
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "8787:8787"
    volumes:
      - ./data:/app/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
